import { CurrentWeather } from "./currentWeather";

export const data = (): CurrentWeather[] => [
  {
    dataCollectTime: new Date("2025-04-06T22:15:00"),
    city: "Gliwice",
    country: "Poland",
    temp_c: 0.1,
    temp_f: 32.2,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/128x128/night/116.png",
    },
    wind_mph: 9.8,
    wind_kph: 15.8,
    wind_dir: "N",
    pressure_mb: 1019,
    pressure_in: 30.09,
    precip_mm: 0,
    precip_in: 0,
    humidity: 59,
    cloud: 50,
    feelslike_c: -4.5,
    feelslike_f: 24,
    vis_km: 10,
    vis_miles: 6,
    uv: 0,
  },
  {
    dataCollectTime: new Date("2025-04-06T22:15:00"),
    city: "Hamburg",
    country: "Germany",
    temp_c: 4.2,
    temp_f: 39.6,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
    },
    wind_mph: 2.2,
    wind_kph: 3.6,
    wind_dir: "ESE",
    pressure_mb: 1027,
    pressure_in: 30.33,
    precip_mm: 0,
    precip_in: 0,
    humidity: 48,
    cloud: 0,
    feelslike_c: 3.8,
    feelslike_f: 38.9,
    vis_km: 10,
    vis_miles: 6,
    uv: 0,
  },
];
